Logical: GenomicStudy
Title: "Genomic Study"
Description: "A Genomic Study is a set of files and procedures that are performed to generate and analyze genomic data."
* ^baseDefinition = "http://hl7.org/fhir/StructureDefinition/DomainResource"
* ^status = #draft
* identifier 0..1 Identifier 
  "An identifier for this genomic study" "An identifier for this genomic study"
* status 0..1 CodeableConcept
  "The status of the genomic study"
* type 0..1 CodeableConcept
  "The type of the study"
* subject 1..1 Reference(Patient)
  "The subject of the genomic study" "The subject of the genomic study"
* encounter 0..1 Reference(Encounter)
  "The healthcare encounter with which this genomics study is associated"
* startDate 0..1 dateTime
  "When the genomic study was started"
* basedOn 0..* Reference(ServiceRequest or Task)
  "Event resources that the genomic study is based on"
* referrer 0..1 Reference(Practitioner or PractitionerRole)
  "Healthcare professional(s) who requested or referred the genomic study"
* interpreter 0..* Reference(Practitioner or PractitionerRole)
  "Healthcare professional(s) who interpreted the genomic study"
* endpoint 0..* Endpoint
  "The endpoint for the genomic study"
//* reason 0..* CodeableReference  -- note, not part of R4
* reason[x] 0..* CodeableConcept or Reference(Condition or Observation)
  "Why the genomic study was performed"
//* reasonCode 0..* CodeableConcept
//  "Here is a reason code"
// we may add more later
//* reasonReference 0..* Reference(Condition or Observation)
//  "Here is a reason reference"
* note 0..* Annotation
  "User-defined notes related to the genomic study"
* description 0..1 string
  "A description of the genomic study"
* genomicAnalysis 0..* BackboneElement
  "Genomic Analysis"
  * identifier 0..* Identifier "Identifier(s) for the analysis"
  * methodType 0..* CodeableConcept "Type of the method(s) used in the analysis"
  * protocolDefinition 0..* Reference(ActivityDefinition) "The defined protocol that describes the analysis"
  //* protocolPerformed 0..* CodeableReference -- note, not part of R4
  * protocolPerformed 0..* Reference(Procedure) "The protocol that was actually performed for the analysis"
  * performer 0..* Reference(Practitioner 
                             or PractitionerRole 
                             or Organization 
                             or CareTeam 
                             or Patient 
                             or Device 
                             or RelatedPerson)
    "The organization, healthcare professional(s), or others who participated in performing this study"
  * device 0..* Device "The device(s) used for the analysis (e.g., sequencers)"
  * genomicFile 0..* Reference(DocumentReference) "Genomic data file(s) used in the analysis"
  * genomicAssay 0..* BackboneElement "Genomic Assay"
    * identifier 0..* Identifier "Identifier(s) for the assay"
    * specimen 0..1 Reference(Specimen) "The specimen used in the assay"
    * subject 0..1 Reference(Patient) "The subject of the assay"
    * date 0..1 dateTime "The date of the assay"
    * regionStudied 0..1 Reference(DocumentReference) "Genomic region studied by the assay"
    * genomicFile 0..* Reference(DocumentReference) "File(s) containing genomic data generated by the assay"
